In [2]:
import numpy as np

In [49]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


In [7]:
a[a < 0]
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [50]:
#1 
(a < 0).sum()

4

TypeError: '<' not supported between instances of 'list' and 'int'

In [10]:
#2
(a >= 0).sum()

8

#3

In [ ]:
pos_and_even = pos_num[pos_num]

In [15]:
#4
a = np.array(a)
print (a + 3)



[ 7 13 15 26  1  2  3  3  3 -3  6 -4]


In [52]:
sum_3 = a[(a + 3) > 0]

len(sum_3)

10

In [53]:
#5

squared_a = a ** 2
print('new mean is {}.'.format(squared_a_mean))



array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [18]:
a.mean()

74.0

In [19]:
a.std()

144.0243035046516

In [20]:
a

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [21]:
#6

a = np.array(a)
print (a + 74)

[ 90 174 218 603  78  75  74  74  74 110  83 123]


In [22]:
a

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [23]:
a = np.array(a)
print (a - 74)

[-58  26  70 455 -70 -73 -74 -74 -74 -38 -65 -25]


In [24]:
a

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [25]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [26]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [28]:
#set up
#1

sum_of_a = sum(a)
print (sum_of_a)

55


In [29]:
#2
min_of_a = min(a)
print (min_of_a)

1


In [30]:
#3

max_of_a = max(a)
print (max_of_a)

10


In [47]:
#4

mean_of_a = np.mean(a)
print (mean_of_a)

5.5


In [33]:
#5

from functools import reduce

In [34]:
reduce(lambda x, y: x*y, [a])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [46]:


product_of_a = np.prod(a)

print(product_of_a)

3628800


In [38]:
#6

squares_of_a = np.square(a)
print (squares_of_a)

[  1   4   9  16  25  36  49  64  81 100]


In [42]:
#7 

odds_in_a = [num for num in a if num % 2 == 1]
  
print(odds_in_a)

[1, 3, 5, 7, 9]


In [43]:
#8

evens_in_a = [num for num in a if num % 2 == 0]

print(evens_in_a)

[2, 4, 6, 8, 10]
